config/routes.rb
Rails.application.routes.draw do
  root "public#main"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Routes for user sign up, login, and logout
  # resources :users, only: [ :index, :new, :create, :show ] # Sign up, and view user
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/profile", to: "users#profile", as: :profile

  # get "/subscription_view", as: :sub_mailer

  # Subscription Route
  post "users/:id/subscribe/", to: "users#sub", as: :subscription
  delete "users/:id/unsubscribe/", to: "users#unsub", as: :unsubscription

  # Routes for posts, categories, and comments
  resources :categories

  resources :users do
    resources :comments
  end

  resources :posts do
    resources :comments
    resources :sections, only: [ :create, :edit, :update, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Rerouting unknown routes to route
  get "*path" => redirect("/")
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password

  has_and_belongs_to_many :subscribers, class_name: "User", join_table: "subscriptions", foreign_key: "subscriber_id"
  has_and_belongs_to_many :users, class_name: "User", join_table: "subscriptions", foreign_key: "user_id"

  has_many :posts, dependent: :destroy
  has_many :authored_comments, class_name: "Comment", foreign_key: "commenter_id", dependent: :destroy
  has_many :comments, class_name: "Comment", as: :commentable, dependent: :destroy

  def is_admin?
    admin
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Authorization

  before_action :authorize_user, only: [ :sub, :unsub, :profile ]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    # puts
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "User successfully created!"
    else
      # flash.now[:alert] = "Invalid inputs."
      redirect_to new_user_path, alert: "Invalid inputs, try again!"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(session[:user_id])
  end

  def sub
    @user = User.find(params[:id])
    @current_user = User.find(session[:user_id])

    unless @user.subscribers.include?(@current_user)
      @user.subscribers << @current_user
      redirect_to @user, notice: "You have subscribed to #{@user.name}"
    else
      redirect_to @user, alert: "Already subscribed to #{@user.name}."
    end
  end

  def unsub
    @user = User.find(params[:id])
    @current_user = User.find(session[:user_id])

    if @user.subscribers.include?(@current_user)
      @user.subscribers.delete(@current_user)
      redirect_to @user, notice: "You have unsubscribed from #{@user.name}"
    else
      redirect_to @user, alert: "You are not subscribed to #{@user.name}"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<div class="max-w-full md:max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <h5 class="oswald-font mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white"><%= user.name %></h5>
    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto, dicta! Architecto voluptatum nisi facere minima recusandae eum aspernatur nostrum ducimus, nemo praesentium quod saepe earum. Vel iste adipisci sed omnis!</p>
    <%= link_to user_path(user) do %>
      <div class="inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white button-primary rounded-lg">
          Visit page
          <svg class="rtl:rotate-180 w-3.5 h-3.5 ms-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
      </div>
    <% end %>
</div>

app/views/users/index.html.erb
<!-- <div class="flex flex-wrap py-12 justify-evenly gap-y-8"> -->
<div class="px-6 flex justify-center">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-4 gap-8 py-12" >
    <%= render partial: "user", collection: @users %>
  </div>
</div>

app/views/users/new.html.erb
<!-- app/views/sessions/new.html.erb -->

<div class="flex min-h-full flex-col items-start-start px-6 py-4 lg:px-8">

  <div class="sm:mx-auto sm:w-full sm:max-w-sm">
    <h2 class="mt-10 text-2xl/9 font-bold tracking-tight text-gray-900">Create a new account</h2>
  </div>
  <%= form_with model: @user, class: "mt-10 sm:mx-auto sm:w-full sm:max-w-sm" do |form| %>
    <div>
      <%= form.label :email_address, class: "block text-sm/6 font-medium text-gray-900" %>
      <div class="mt-2">
        <%= form.text_field :email, required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
      </div>
    </div>
    <hr>
    <div>
      <%= form.label :name, class: "block text-sm/6 font-medium text-gray-900" %>
      <%= form.text_field :name, required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
    </div>
    <hr>
    <div>
      <%= form.label :password, class: "block text-sm/6 font-medium text-gray-900" %>
      <%= form.password_field :password, required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
    </div>
    <hr>
    <div>
      <%= form.label :password_confirmation, class: "block text-sm/6 font-medium text-gray-900" %>
      <%= form.password_field :password_confirmation, required: true, class: "block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6" %>
    </div>
    <hr>
    <div>
      <%= form.submit 'Sign Up', class: "flex w-full justify-center rounded-md button-primary px-3 py-1.5 text-sm/6 font-semibold text-white shadow-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" %>
    </div>
    <% if flash[:error] %>
      <% # user.messages.each do |error| %>
        <div><%= flash[:error] %></div>
      <% # end %>
    <% end %>
  <% end %>
</div>

app/views/users/profile.html.erb
  <div class="px-12 pt-12 pb-4 bg-secondary">
    <div class="flex justify-between items-center">
      <h2 class="text-white oswald-font text-5xl font-medium"><%= @user.name %></h2>
    </div>
  </div>
  <div>
    <%= render partial: "posts/profile_post_bar", collection: @user.posts, as: :post %>
    <div class="flex justify-between py-12 px-12 items-center">
      <div class="flex items-center gap-x-3">
        <%= link_to new_post_path, class: "p-1 button-primary text-white rounded-lg" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="size-7">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
        <% end %>

        <div class="text-4xl oswald-font font-semibold text-gray-900">Create New Post</div>
      </div>
    </div>
  </div>
  <%= render partial: "comments/comments", locals: { commentable: @user, comments: @user.comments } %>

app/views/users/show.html.erb
  <div class="px-12 pt-12 pb-4 bg-secondary">
    <div class="flex justify-between items-center">
      <h2 class="text-white oswald-font text-5xl font-medium"><%= @user.name %></h2>
      <% if logged_in? %>
        <% unless subscribed?(@user) %>
          <%= form_with url: subscription_path(@user), method: :post do %>
            <%= submit_tag "Subscribe", class: "hidden md:block button-primary text-white py-2 px-4 rounded"%>
            <%= button_tag class: "block md:hidden", type: "submit" do %>
              <div class="button-primary text-white py-2 px-4 rounded">
                <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 20">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 19-6-5-6 5V2a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v17Z"></path>
                </svg>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <%= form_with url: unsubscription_path(@user), method: :delete do %>
            <%= submit_tag "Unsubscribe", class: "hidden md:block button-primary text-white py-2 px-4 rounded"%>
            <%= button_tag class: "block md:hidden", type: "submit" do %>
              <div class="button-primary text-white py-2 px-4 rounded">
                <svg class="w-6 h-6 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 20">
                  <path fill="currentColor" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 19-6-5-6 5V2a1 1 0 0 1 1-1h10a1 1 0 0 1 1 1v17Z"></path>
                </svg>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div>
    <% if @user.posts.size > 0 %>
      <%= render partial: "posts/post_bar", collection: @user.posts, as: :post %>
    <% else %>
      <div class="flex justify-between gap-x-6 py-12 px-12 items-center">
        <p class="text-4xl oswald-font font-semibold text-gray-900">No Posts Yet</p>
      </div>
    <% end %>
  </div>
  <%= render partial: "comments/comments", locals: { commentable: @user, comments: @user.comments } %>