config/routes.rb
Rails.application.routes.draw do
  root "public#main"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Routes for user sign up, login, and logout
  # resources :users, only: [ :index, :new, :create, :show ] # Sign up, and view user
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/profile", to: "users#profile", as: :profile

  # get "/subscription_view", as: :sub_mailer

  # Subscription Route
  post "users/:id/subscribe/", to: "users#sub", as: :subscription
  delete "users/:id/unsubscribe/", to: "users#unsub", as: :unsubscription

  # Routes for posts, categories, and comments
  resources :categories

  resources :users do
    resources :comments
  end

  resources :posts do
    resources :comments
    resources :sections, only: [ :create, :edit, :update, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Rerouting unknown routes to route
  get "*path" => redirect("/")
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5, maximum: 50 }

  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :sections, dependent: :destroy
  accepts_nested_attributes_for :sections, allow_destroy: true

  after_create :notify_subscribers

  private

  def notify_subscribers
    user.subscribers.each do |subscriber|
      SubscriptionMailer.new_post_notification(self, subscriber).deliver_later
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include Authorization

  before_action :authorize_user
  # before_action :authorize_user_specific, only: [ :destroy ]
  skip_before_action :authorize_user, only: [ :index, :show ]

  def index
    # @posts = Post.all
    p "#{params[:category_ids]} -----------------------------------------"
    if params[:category_ids].present?
      @posts = Post.joins(:categories).where(categories: { id: params[:category_ids] }).distinct
    else
      @posts = Post.all
    end
    @categories = Category.order(name: :asc)
  end

  def new
    @post = Post.new
    @post.sections.build
    @categories = Category.all
  end

  def create
    @post = Post.new(title: post_params[:title], user_id: session[:user_id])
    if @post.save
      if post_params[:category_ids].present?
        category_ids = post_params[:category_ids].map(&:to_i)
        @post.categories = Category.find(category_ids)
      end
      p "HERE 1 --------------------------------------------"
      if post_params[:sections_attributes].present?
        p "HERE 2 ------------------------------------------"
        p post_params
        p post_params[:sections_attributes]
        post_params[:sections_attributes].each do |index, section_params|
          p "Section Params"
          p section_params
          # p section_params[:body]
          @post.sections.create(title: section_params[:title], body: section_params[:body])
        end
      end

      redirect_to @post, notice: "Post created."
    else
      redirect_to new_post_path, alert: "Could not create post"
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @categories = Category.all
  end

  def update
    @post = Post.find(params[:id])

    # Update categories if provided
    if post_params[:category_ids].present?
      category_ids = post_params[:category_ids].map(&:to_i)
      @post.categories = Category.find(category_ids)
    end

    # Update the title and sections
    if post_params[:sections_attributes].present?
      post_params[:sections_attributes].each do |index, section_params|
        if section_params[:_destroy] == "1"
          section = @post.sections.find_by(id: section_params[:id])
          section&.destroy if section
        else
          section = @post.sections.find_or_initialize_by(id: section_params[:id])
          section.update(section_params.except(:_destroy))
        end
      end
    end
    @post.assign_attributes(post_params.except(:sections_attributes, :category_ids))
    # unless post_params[:sections_attributes]
    #   @post.sections.destroy_all
    # end

    if @post.save
      redirect_to @post, notice: "Edit successful."
    else
      redirect_to edit_post_path(@post), alert: "Edit not successful."
    end
  end

  def destroy
    p "DELETING ----------------------------"
    @post = Post.find(params[:id])
    if @post.destroy
      p "DELETED -------------------------------------"
      redirect_to profile_path, notice: "Post deleted."
    else
      p "FAILED ---------------------------------"
      redirect_to @post, alert: "Could not delete post."
    end
  end

  def post_params
    params.require(:post).permit(:title, category_ids: [], sections_attributes: [ :id, :title, :body, :_destroy ])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_filter.html.erb
<nav class="border-gray-200 bg-gray-50 dark:bg-gray-800 dark:border-gray-700 px-12 p-6">
  <div class=" flex flex-wrap items-center justify-between">
    <div class="flex items-center space-x-3 rtl:space-x-reverse">
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Categories</span>
    </div>
    <button data-collapse-toggle="navbar-hamburger" type="button" class="inline-flex items-center justify-center p-2 w-10 h-10 text-sm text-gray-500 rounded-lg hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-hamburger" aria-expanded="false">
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
      </svg>
    </button>
    <div class="hidden w-full" id="navbar-hamburger">
      <%= form_with url: posts_path, method: :get, local: true do %>
        <ul class="flex flex-col font-medium mt-4 rounded-lg bg-gray-50 dark:bg-gray-800 dark:border-gray-700">
          <% categories.each do |category| %>
            <!-- <li>
              <a href="#" class="block py-2 px-3 text-gray-600 rounded" aria-current="page"><%= category.name %></a>
            </li> -->
            <div class="flex items-center gap-x-2">
              <%= check_box_tag 'category_ids[]', category.id, params[:category_ids]&.include?(category.id.to_s) %>
              <%= label_tag "category_ids_#{category.id}", category.name %>
            </div>
          <% end %>
        </ul>
        <div class="mt-3">
          <%= submit_tag 'Filter', class: "bg-secondary text-white px-4 py-2 rounded" %>
          <%= link_to 'Clear Filters', posts_path, class: "bg-secondary text-white px-4 py-2.5 rounded" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<hr>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |form| %>
  <div class="px-12 pt-12 pb-4 bg-secondary mb-6">
    <div class="flex justify-between items-center">
      <div class="flex items-center mb-4 gap-x-6">
        <%= form.text_field :title, class: "rounded-3xl oswald-font text-5xl font-medium", placeholder: "Enter Title" %>
      </div>
      <div>
        <%= button_tag type: "submit", class: "p-1 button-primary text-white rounded-lg" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="size-10">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
          </svg>
        <% end %>
      </div>
    </div>

    <div class="flex items-center gap-x-2">
      <h3 class="text-white text-xl">Categories</h3>
      <button data-collapse-toggle="navbar-hamburger" type="button" class="inline-flex items-center justify-center text-sm text-gray-500 rounded-lg hover:bg-gray-100 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-hamburger" aria-expanded="false">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
        </svg>
      </button>
    </div>

    <div class="hidden w-full" id="navbar-hamburger">
      <ul class="flex flex-wrap gap-x-6 font-medium mt-4 rounded-lg bg-secondary dark:bg-gray-800 dark:border-gray-700">
        <% @categories.each do |category| %>
          <div class="flex items-center gap-x-2 text-white">
            <%= check_box_tag 'category_ids[]', category.id, post.category_ids.include?(category.id) %>
            <%= label_tag "category_ids_#{category.id}", category.name %>
          </div>
        <% end %>
      </ul>
    </div>
  </div>

  <div data-controller="sections">
    <!-- Sections Container -->
    <div id="sections" data-sections-target="container">
      <% post.sections.each do |section| %>
        <div class="nested-fields flex flex-col">
          <%= form.fields_for :sections, section do |section_form|%>
            <div class="px-12 pb-2 flex justify-between">
              <%= section_form.text_field :title, value: section.title, placeholder: "Section Title" %>
              <% if action_name == "new" %>
                <button class="remove-section button-secondary p-2" data-action="sections#remove">
                  <svg xmlns="http://www.w3.org/2000/svg" fill="white" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" class="size-6">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
                  </svg>
                </button>
              <% elsif action_name == "edit" %>
                <div class="flex items-center gap-x-1">
                  <%= section_form.check_box :_destroy, { class: "remove-section" }, "1", "0" %>
                  <%= section_form.label :_destroy, "Remove" %>
                </div>
              <% end %>
            </div>
            <div class="self-stretch flex px-12" data-controller="character-counter">
              <%= section_form.text_area :body, value: section.body, placeholder: "Section Body", class: "flex-1 min-h-96", data: { "character-counter-target": "input", "character-counter-max-length": 11500 } %>
            </div>
            <p class="px-12 text-right text-sm text-gray-500" data-character-counter-target="counter">0 / 11500</p>
          <% end %>
        </div>
      <% end %>
    </div>

    <!-- Add Section Button -->
    <button class="px-12 gap-x-1 mt-4 mb-16 flex items-center" id="add-section" data-action="sections#add">
      <div class="button-primary text-white rounded-full">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
        </svg>
      </div>
      <div class="text-lg">
        Add Section
      </div>
    </button>

    <!-- Hidden Template -->
    <template id="new-section-template" data-sections-target="template">
      <div class="nested-fields flex flex-col mt-8">
        <%= form.fields_for :sections, Section.new do |section_form|%>
          <div class="px-12 pb-2 flex justify-between">
            <%= section_form.text_field :title, placeholder: "Section Title" %>
            <button class="remove-section button-secondary p-2" data-action="sections#remove">
              <svg xmlns="http://www.w3.org/2000/svg" fill="white" viewBox="0 0 24 24" stroke-width="1.5" stroke="white" class="size-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <div class="self-stretch flex px-12" data-controller="character-counter">
            <%= section_form.text_area :body, placeholder: "Section Body", class: "flex-1 min-h-96", data: { "character-counter-target": "input", "character-counter-max-length": 11500 } %>
          </div>
          <p class="px-12 text-right text-sm text-gray-500" data-character-counter-target="counter">0 / 11500</p>
          <%= section_form.hidden_field :_destroy, value: "0" %>
        <% end %>
      </div>
    </template>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="px-12 pt-12 pb-4 bg-secondary">
  <div class="flex justify-between items-center">
    <h2 class="text-white oswald-font text-5xl font-medium mb-4"><%= @post.title %></h2>
  </div>
  <div>
    <h3 class="text-white">
      Categories:
      <% if @post.categories.size > 0 %>
        <% @post.categories.each_with_index do |category, index| %>
          <% if index == @post.categories.size - 1 %>
            <%= category.name %>
          <% else %>
            <%= category.name %>,
          <% end %>
        <% end %>
      <% else %>
        Other
      <% end %>
    </h3>
  </div>
</div>

app/views/posts/_post_bar.html.erb
<li class="flex justify-between gap-x-6 py-12 px-12 items-center">
  <div class="flex min-w-0 gap-x-4">
    <div class="min-w-0 flex-auto">
      <p class="text-4xl oswald-font font-semibold text-gray-900"><%= link_to post.title, post_path(post) %></p>
      <p class="mt-1 truncate text-base text-gray-500">Categories:
        <% post.categories.each_with_index do |category, index| %>
          <% if index == post.categories.size - 1 %>
            <%= category.name %>
          <% else %>
            <%= category.name %>,
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
  <div class="hidden shrink-0 md:flex md:flex-col md:items-end">
    <p class="text-base text-gray-900">Author: <%= link_to post.user.name, user_path(post.user) %></p>
    <p class="mt-1 text-xs/5 text-gray-500">Last edited at <time datetime="2023-01-23T13:23Z"><%= post.updated_at %></time></p>
  </div>
</li>

app/views/posts/_profile_post_bar.html.erb
<li class="flex justify-between gap-x-6 py-12 px-12 items-center">
  <div class="flex min-w-0 gap-x-4">
    <div class="min-w-0 flex-auto">
      <p class="text-4xl oswald-font font-semibold text-gray-900"><%= link_to post.title, post_path(post) %></p>
      <p class="mt-1 truncate text-base text-gray-500">Categories:
        <% if post.categories.present? %>
          <% post.categories.each_with_index do |category, index| %>
            <% if index == post.categories.size - 1 %>
              <%= category.name %>
            <% else %>
              <%= category.name %>,
            <% end %>
          <% end %>
        <% else %>
          Other
        <% end %>
      </p>
    </div>
  </div>
  <div class="hidden shrink-0 md:flex md:flex-col md:items-end">
    <div class="flex">
      <%= link_to edit_post_path(post) do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
          <path stroke-linecap="round" stroke-linejoin="round" d="m16.862 4.487 1.687-1.688a1.875 1.875 0 1 1 2.652 2.652L10.582 16.07a4.5 4.5 0 0 1-1.897 1.13L6 18l.8-2.685a4.5 4.5 0 0 1 1.13-1.897l8.932-8.931Zm0 0L19.5 7.125M18 14v4.75A2.25 2.25 0 0 1 15.75 21H5.25A2.25 2.25 0 0 1 3 18.75V8.25A2.25 2.25 0 0 1 5.25 6H10" />
        </svg>
      <% end %>
      <%= form_with url: post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, turbo: false do %>
        <%= button_tag class: "danger-color" do %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15 12H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
        <% end %>
      <% end %>
    </div>
    <p class="mt-1 text-xs/5 text-gray-500">Last edited at <time datetime="2023-01-23T13:23Z"><%= post.updated_at %></time></p>
  </div>
</li>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<%= render partial: "filter", locals: { categories: @categories }%>

<ul role="list" class="divide-y divide-gray-100">
  <%= render partial: "post_bar", collection: @posts, as: :post %>
</ul>

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<%= render "post" %>

<div>
  <% @post.sections.each_with_index do |section, index| %>
    <h3 class="bg-primary px-12 pt-6 pb-2 text-3xl text-white oswald-font"><%= index+1 %>. <%= section.title %></h3>
    <p class="px-12 py-8"><%= section.body %></p>
  <% end %>
</div>


<%= render partial: "comments/comments", locals: { commentable: @post, comments: @post.comments } %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>