config/routes.rb
Rails.application.routes.draw do
  root "public#main"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Routes for user sign up, login, and logout
  # resources :users, only: [ :index, :new, :create, :show ] # Sign up, and view user
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/profile", to: "users#profile", as: :profile

  # get "/subscription_view", as: :sub_mailer

  # Subscription Route
  post "users/:id/subscribe/", to: "users#sub", as: :subscription
  delete "users/:id/unsubscribe/", to: "users#unsub", as: :unsubscription

  # Routes for posts, categories, and comments
  resources :categories

  resources :users do
    resources :comments
  end

  resources :posts do
    resources :comments
    resources :sections, only: [ :create, :edit, :update, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Rerouting unknown routes to route
  get "*path" => redirect("/")
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { minimum: 3, maximum: 50 }

  has_and_belongs_to_many :posts
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Authorization

  before_action :authorize_admin, only: [ :new, :create, :update, :destroy, :edit ]

  def index
    @categories = Category.all
    @category = Category.new
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      redirect_to categories_path, alert: "Could not make new category."
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
    @category = Category.find(params[:id])
    name = @category.name
    if @category.destroy
      redirect_to categories_path, alert: "Category \'#{name}\' deleted"
    end
  end

  private

  def category_params
    p params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<li class="flex justify-between gap-x-6 py-5 px-6">
  <div class="flex flex-1 min-w-0 gap-x-4">
    <div class="min-w-0 flex justify-between flex-1 items-center">
      <p class="text-sm/12 font-semibold text-gray-900"><%= link_to category.name, category_path(category) %></p>
      <% if is_admin_helper? %>
        <%= form_with url: category_path(category), method: :delete do %>
          <%= submit_tag "Delete", class: "button-primary text-white py-2 px-4 rounded" %>
        <% end %>
      <% end %>
    </div>
  </div>
</li>

app/views/categories/_new.html.erb
<li class="flex justify-between gap-x-6 py-5 px-6">
  <div class="flex flex-1 min-w-0 gap-x-4">
    <%= form_with model: @category, local: true, class: "flex items-center gap-x-4 text-sm/12 font-semibold text-gray-900" do |form| %>
      <%= form.label "New Category:" %>
      <div class="rounded-lg overflow-hidden border-secondary">
        <%= form.text_field :name, class: "border-none", placeholder: "Category Name" %>
        <%= form.submit "Add", class: "button-secondary py-2 px-4 text-white" %>
      </div>
    <% end %>
  </div>
</li>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<div class="py-6 antialiased">
  <div class="max-w-screen-xl px-6">
    <div class="mb-4 flex items-center justify-between gap-4 md:mb-8">
      <h2 class="text-xl font-semibold text-gray-900 dark:text-white sm:text-2xl">Blog categories</h2>
    </div>
  </div>
</div>
<ul role="list" class="divide-y divide-gray-100">
  <%= render partial: "category", collection: @categories %>
  <% if is_admin_helper? %>
    <%= render partial: "new" %>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>
<p><%= render partial: "posts/post_bar", collection: @category.posts, as: :post %></p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>