config/routes.rb
Rails.application.routes.draw do
  root "public#main"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Routes for user sign up, login, and logout
  # resources :users, only: [ :index, :new, :create, :show ] # Sign up, and view user
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout
  get "/profile", to: "users#profile", as: :profile

  # get "/subscription_view", as: :sub_mailer

  # Subscription Route
  post "users/:id/subscribe/", to: "users#sub", as: :subscription
  delete "users/:id/unsubscribe/", to: "users#unsub", as: :unsubscription

  # Routes for posts, categories, and comments
  resources :categories

  resources :users do
    resources :comments
  end

  resources :posts do
    resources :comments
    resources :sections, only: [ :create, :edit, :update, :destroy ]
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Rerouting unknown routes to route
  get "*path" => redirect("/")
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  add_flash_types :log_success, :log_fail
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    session[:user_id] ? true : false
  end

  def get_user
    User.find_by(id: session[:user_id])
  end

  def is_admin_helper?
    if logged_in?
      User.find(session[:user_id]).is_admin?
    else
      false
    end
  end

  def is_user_s?(other)
    other.user.id == session[:user_id] ? true : false
  end
end

app/views/application/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="flash-message text-white <%= type %>-style p-4 flex items-center justify-between space-x-4 border" role="alert">
    <span class="flex-1 text-sm">
      <%= message %>
    </span>
    <button class="text-white hover:text-gray-700" onclick="this.parentElement.style.display='none';">
      &times;
    </button>
  </div>
  <hr>
<% end %>

app/views/application/_navbar.html.erb
<div class="background-primary lg:bg-white flex justify-between items-center py-4 px-12">
  <%= render partial: "toggle_navbar" %>
  <ul class="hidden shrink-0 lg:flex gap-x-20 items-center flex-1">
    <li><%= link_to "Home", root_path, class: "text-gray-500 hover:text-gray-700 px-0 py-2" %></li>
    <li><%= link_to "Bloggers", users_path, class: "text-gray-500 hover:text-gray-700 px-0 py-2" %></li>
    <li><%= link_to "Categories", categories_path, class: "text-gray-500 hover:text-gray-700 px-0 py-2" %></li>
    <li><%= link_to "Blogs", posts_path, class: "text-gray-500 hover:text-gray-700 px-0 py-2" %></li>
  </ul>

  <div class="hidden lg:flex flex-1 justify-end gap-x-4">
    <% unless logged_in? %>
      <%= button_to "Login", login_path, method: :get, class: "button-primary text-white py-2 px-4 rounded" %>
      <%= button_to "Sign up", new_user_path, method: :get, class: "button-primary text-white py-2 px-4 rounded" %>
    <% else %>
      <%= button_to "My Profile", profile_path, method: :get, class: "button-primary-invert py-2 px-4 rounded" %>
      <%= button_to "New Post", new_post_path, method: :get, class: "button-primary-invert py-2 px-4 rounded" %>
      <%= form_with url: logout_path, method: :delete do %>
        <%= submit_tag "Logout", class: "button-primary text-white py-2 px-4 rounded" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/application/_toggle_navbar.html.erb
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex justify-center items-center text-sm text-gray-500 rounded-lg lg:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200">
   <svg class="w-6 h-6" aria-hidden="true" fill="white" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
   <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
   </svg>
</button>

<aside id="default-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full" aria-label="Sidebar">
   <div class="h-full px-3 py-12 overflow-y-auto bg-gray-50 dark:bg-gray-800">
      <ul class="space-y-2 font-medium">
        <li>
          <%= link_to "Home", root_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
        </li>
        <li>
          <%= link_to "Bloggers", users_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
        </li>
        <li>
          <%= link_to "Categories", categories_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
        </li>
        <li>
          <%= link_to "Blogs", posts_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
        </li>
        <hr>
        <% unless logged_in? %>
          <li>
            <%= link_to "Login", login_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
          </li>
          <li>
            <%= link_to "Sign up", new_user_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
          </li>
        <% else %>
          <li>
            <%= link_to "My Profile", profile_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
          </li>
          <li>
            <%= link_to "New Post", new_post_path, class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
          </li>
          <hr>
          <li>
            <%= form_with url: logout_path, method: :delete do %>
              <%= submit_tag "Logout", class: "flex items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-100 dark:hover:bg-gray-700 group" %>
            <% end %>
          </li>
        <% end %>
      </ul>
   </div>
</aside>